### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by BurhanBudak** [herlesupreeth/SetAPN#1]
So I just need to compile the app? Can I install with Magisk? If this helps VoLTE for all "uncertified" phones, you should reconsider uploading this to the open source Magisk repo. This reminds me off Xiaomi way to implementing IMS.

**Comment by herlesupreeth** [comment]
> So I just need to compile the app

Yep, just make sure to keep hold of signing key. Since this app uses Carrier Privileges you will need to put that key in SIM card for app to work effectively

> Can I install with Magisk?

Sorry, I dont know whether its possible or not

> If this helps VoLTE for all "uncertified" phones, you should reconsider uploading this to the open source Magisk repo

It could have helped all the phones provided the modem vendors did not place another lock at firmware level (sigh). This app currently allows you to set APNs but its ultimately the phone OS and modem firmware to decide whether to take these APN settings or not

**Comment by BurhanBudak** [comment]
>Sorry, I dont know whether its possible or not
It could have helped all the phones provided the modem vendors did not place another lock at firmware level (sigh). This app currently allows you to set APNs but its ultimately the phone OS and modem firmware to decide whether to take these APN settings or not

This is a root solution. As carriers dont want to support enthusiastic unknown budget brands, there wont be a official support firmware anymore. Also magisk installs modules with zip files. Now I dont want to bootloop my phone from 2016. I have tried the QPTS/PDC/EFStool trick but I dont have the carrier mbn profile on my phone, maybe Telecom DE will work with Telia SE. My MVNO will roll out VoLTE/VoWifi this month after 4 years of wait.

**Comment by BurhanBudak** [comment]
>Yep, just make sure to keep hold of signing key. Since this app uses Carrier Privileges you will need to put that key in SIM card for app to work effectively

Im sorry how do I get that key? Is it on the SIM-card holder I got with the mail?

**Comment by herlesupreeth** [comment]
Here is the procedure to sign your generated APK - https://developer.android.com/studio/publish/app-signing

Once you have signed and generated the APK - here it explains how to fetch the SHA1 key of the certificate - https://stackoverflow.com/questions/27609442/how-to-get-the-sha-1-fingerprint-certificate-in-android-studio-for-debug-mode
